config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :districts
    resources :divisions
    resources :customers
    get 'dashboard', to: 'dashboard#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :division
  belongs_to :district
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :division
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :customers, dependent: :destroy
  has_many :districts, dependent: :destroy
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  layout 'admin'
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::DashboardController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  
  def index
    @customers = Customer.all.order("Created_at DESC")
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    if @customer.save
      flash[:success] = "Customer Create Successfully."
      redirect_to admin_customers_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "Customer details update successfully."
      redirect_to admin_customers_path
    else
      render 'edit'
    end
  end

  def destroy
    if @customer.destroy
      flash[:danger] = "Customer deleted successfully"
      redirect_to admin_customers_path
    else
      flash[:danger] = "Something went wrong!"
      redirect_to admin_customers_path
    end
  end
  

  private
  def customer_params
    params.require(:customer).permit(:name, :mobilenumber, :urgentnumber, :presentaddress, :permanentaddress, :division_id, :district_id)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @customers = Customer.all
    @divisions = Division.all
    @districts = District.all
  end
end

app/controllers/admin/districts_controller.rb
class Admin::DistrictsController < Admin::DashboardController
  before_action :set_district, only: [:show, :edit, :update, :destroy]
  
  def index
    @districts = District.all
  end

  def new
    @district = District.new
  end

  def create
    @district = District.create(district_params)
    if @district.save
      flash[:success] = "District Create Successfully."
      redirect_to admin_districts_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @district.update(district_params)
      flash[:success] = "District details update successfully."
      redirect_to admin_districts_path
    else
      render 'edit'
    end
  end

  def destroy
    if @district.destroy
      flash[:danger] = "District deleted successfully"
      redirect_to admin_districts_path
    else
      flash[:danger] = "Something went wrong!"
      redirect_to admin_districts_path
    end
  end
  

  private
  def district_params
    params.require(:district).permit(:name, :division_id)
  end

  def set_district
    @district = District.find(params[:id])
  end
end

app/controllers/admin/divisions_controller.rb
class Admin::DivisionsController < Admin::DashboardController
  before_action :set_division, only: [:show, :edit, :update, :destroy]
  
  def index
    @divisions = Division.all
  end

  def new
    @division = Division.new
  end

  def create
    @division = Division.create(division_params)
    if @division.save
      flash[:success] = "Division Create Successfully."
      redirect_to admin_divisions_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @division.update(division_params)
      flash[:success] = "Division details update successfully."
      redirect_to admin_divisions_path
    else
      render 'edit'
    end
  end

  def destroy
    if @division.destroy
      flash[:danger] = "Division deleted successfully"
      redirect_to admin_divisions_path
    else
      flash[:danger] = "Something went wrong!"
      redirect_to admin_divisions_path
    end
  end
  

  private
  def division_params
    params.require(:division).permit(:name)
  end

  def set_division
    @division = Division.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/districts_helper.rb
module Admin::DistrictsHelper
end

app/helpers/admin/divisions_helper.rb
module Admin::DivisionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/_form.html.erb
<div class="row d-flex justify-content-center my-5">
  <div class="col-md-5">
    <%= form_for([:admin, @customer]) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Full Name' %>
      </div>
      <div class="form-group">
        <%= f.label :mobilenumber %></br>
        <%= f.text_field :mobilenumber, class: 'form-control', placeholder: 'Mobile Number' %>
      </div>
      <div class="form-group">
        <%= f.label :urgentnumber %></br>
        <%= f.text_field :urgentnumber, class: 'form-control', placeholder: 'Urgent Contact Number' %>
      </div>

      
      <div class="form-row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :division %> </br>
            <%#= f.collection_radio_buttons :division_id, Division.all, :id, :name %>
            <%= f.collection_select(:division_id, Division.all, :id, :name, {:prompt => "Select your division"}, {}) %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :district %>
            <%#= f.collection_radio_buttons :division_id, Division.all, :id, :name %>
            <%= f.collection_select(:district_id, District.all, :id, :name, {:prompt => "Select your District"}, {}) %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :presentaddress %></br>
        <%= f.text_area :presentaddress, class: 'form-control', placeholder: 'Present Address' %>
      </div>
      <div class="form-group">
        <%= f.label :permanentadress %></br>
        <%= f.text_area :permanentaddress, class: 'form-control', placeholder: 'Permanent Address' %>
      </div>

      <%= f.submit(@customer.new_record? ? "Submit" : "Update", class: 'btn btn-sm btn-outline-success') %>
      <%= link_to 'Cancle', admin_customers_path, class: 'btn btn-sm btn-outline-danger' %>
    <% end %>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<%= render 'form' %>

app/views/admin/customers/index.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <h1>All Customers</h1>

    <table class="table table-condensed table-sm table-striped table-bordered">
      <thead>
        <tr>
          <th class="fs-xs">Full Name</th>
          <th class="fs-xs">Division</th>
          <th class="fs-xs">Mobile Number</th>
          <th class="fs-xs">Present Address</th>
          <th class="fs-xs">Permanent Address</th>
          <th class="fs-xs">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td class="fs-xs"><%= customer.name %></td>
          <td class="fs-xs"><%= customer.division.name %></td>
          <td class="fs-xs"><%= customer.mobilenumber %></td>
          <td class="fs-xs"><%= customer.presentaddress %></td>
          <td class="fs-xs"><%= customer.permanentaddress %></td>
          <td class="fs-xs">
            <%= link_to 'View', admin_customer_path(customer), class: 'btn btn-sm btn-outline-info' %>
            <%= link_to 'Edit', edit_admin_customer_path(customer), class: 'btn btn-sm btn-outline-info' %>
            <%= link_to 'Delete', admin_customer_path(customer), class: 'btn btn-sm btn-outline-danger', method: :delete, data: {Confirm: "Are you sure?"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/new.html.erb
<%= render 'form' %>

app/views/admin/customers/show.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <h4 class="card-title">Customer Details</h4>
  </div>
  <div class="col-md-4">
    <%= image_tag  "city-man-person-people-35183.jpg", class: 'img-fluid' %>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <dl class="row">
          <dt class="col-sm-4">Name:</dt>
          <dd class="col-sm-8"><%= @customer.name %></dd>

          <dt class="col-sm-4">Division:</dt>
          <dd class="col-sm-8"><%= @customer.division.name %></dd>

          <dt class="col-sm-4">District:</dt>
          <dd class="col-sm-8"><%= @customer.district.name %></dd>

          <dt class="col-sm-4 text-truncate">Mobile:</dt>
          <dd class="col-sm-8"><%= @customer.mobilenumber %></dd>

          <dt class="col-sm-4">Urgent Contact:</dt>
          <dd class="col-sm-8"><%= @customer.urgentnumber %></dd>

          <dt class="col-sm-4">Present Address:</dt>
          <dd class="col-sm-8"><%= @customer.presentaddress %></dd>

          <dt class="col-sm-4">Permanent Address:</dt>
          <dd class="col-sm-8"><%= @customer.presentaddress %></dd>
        </dl>
      </div>
    </div>
  </div>  
</div>

app/views/admin/dashboard/index.html.erb
<div class="row mt-5">
  <div class="col-md-12">
    <div class="jumbotron bg-warning">
      <p class="lead">Welcome to</p>
      <h1 class="display-3">Macro Marketing</h1>
      <p class="lead mt-5">
        <%= link_to "New Customer", new_admin_customer_path, class: 'btn btn-sm btn-outline-danger' %>
      </p>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="card border-success">
      <div class="card-body">
        <p class="card-text">Total Customer</p>
        <h4 class="card-title"><%= @customers.count %></h4>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card border-success">
      <div class="card-body">
        <p class="card-text">Total Division</p>
        <h4 class="card-title"><%= @divisions.count %></h4>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card border-success">
      <div class="card-body">
        <p class="card-text">Total Districts</p>
        <h4 class="card-title"><%= @districts.count %></h4>
      </div>
    </div>
  </div>
</div>

app/views/admin/districts/_form.html.erb
<div class="row d-flex justify-content-center my-5">
  <div class="col-md-5">
    <h3 class="mb-5">Create New District</h3>
    <%= form_for([:admin, @district]) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Full Name' %>
      </div>
      <div class="form-group">
        <label for="">Division</label>
        <%#= f.collection_radio_buttons :division_id, Division.all, :id, :name %>
        <%= f.collection_select(:division_id, Division.all, :id, :name, {:prompt => "Select your division"}, {}) %>
      </div>

      <%= f.submit(@district.new_record? ? "Submit" : "Update", class: 'btn btn-sm btn-outline-success') %>
      <%= link_to 'Cancle', admin_districts_path, class: 'btn btn-sm btn-outline-danger' %>
    <% end %>
  </div>
</div>

app/views/admin/districts/edit.html.erb
<%= render 'form' %>

app/views/admin/districts/index.html.erb
<div class="row mt-5">
  <div class="col-md-12">
    <h1>All Districts</h1>

    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th>District Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @districts.each do |district| %>
        <tr>
          <td scope="row"><%= district.name %></td>
          <td>
            <%= link_to 'Edit', edit_admin_district_path(district), class: 'btn btn-sm btn-outline-info' %>
            <%= link_to 'Delete', admin_district_path(district), class: 'btn btn-sm btn-outline-danger', method: :delete, data: {Confirm: "Are you sure?"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/districts/new.html.erb
<%= render 'form' %>

app/views/admin/divisions/_form.html.erb
<div class="row d-flex justify-content-center my-5">
  <div class="col-md-5">
    <h3 class="mb-5">Create New Division</h3>
    <%= form_for([:admin, @division]) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Full Name' %>
      </div>

      <%= f.submit(@division.new_record? ? "Submit" : "Update", class: 'btn btn-sm btn-outline-success') %>
      <%= link_to 'Cancle', admin_divisions_path, class: 'btn btn-sm btn-outline-danger' %>
    <% end %>
  </div>
</div>

app/views/admin/divisions/edit.html.erb
<%= render 'form' %>

app/views/admin/divisions/index.html.erb
<div class="row mt-5">
  <div class="col-md-12">
    <h1>All Divisions</h1>

    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th>Division Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @divisions.each do |division| %>
        <tr>
          <td scope="row"><%= division.name %></td>
          <td class="float-right">
            <%= link_to 'View', admin_division_path(division), class: 'btn btn-sm btn-outline-success'  %>
            <%= link_to 'Edit', edit_admin_division_path(division), class: 'btn btn-sm btn-outline-info' %>
            <%= link_to 'Delete', admin_division_path(division), class: 'btn btn-sm btn-outline-danger', method: :delete, data: {Confirm: "Are you sure?"} %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/divisions/new.html.erb
<%= render 'form' %>

app/views/admin/divisions/show.html.erb
<div class="row mt-5">
  <div class="col-md-4">
    <h4 class="card-title">Division Details</h4>
  </div>
  <div class="col-md-8">
    <h4 class="card-title">Divisions Under <%= @division.name %></h4>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="card border-primary">
      <div class="card-body">
        <h3><%= @division.name %></h3>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <dl class="row">
          <dd class="col-sm-8">
            <% @division.districts.each do |divdis| %>
              <span class="badge badge-success">
                <%= divdis.name %>
              </span>
            <% end %>
          </dd>
        </dl>
      </div>
    </div>
  </div>  
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Macrom-Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/admin/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Macrom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/admin/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-danger">
  <div class="container">
    <%= link_to "Macro Marketing", admin_dashboard_path, class: 'navbar-brand' %>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <%= link_to "Dashboard", admin_dashboard_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Customers</a>
          <div class="dropdown-menu" aria-labelledby="dropdownId">
            <%= link_to "All Customers", admin_customers_path, class: 'dropdown-item' %>
            <%= link_to "Create Customer", new_admin_customer_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Divisions</a>
          <div class="dropdown-menu" aria-labelledby="dropdownId">
            <%= link_to "All Divisions", admin_divisions_path, class: 'dropdown-item' %>
            <%= link_to "Create Divisions", new_admin_division_path, class: 'dropdown-item' %>
            <%= link_to "All Districts", admin_districts_path, class: 'dropdown-item' %>
            <%= link_to "Create District", new_admin_district_path, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>